name: NicknameColors
main: MulkiAqi192\NicknameColors\Main
authors: ["ZhorifCraft451", "MulkiAqi192"]
api: [4.0.0]
version: 1.1

commands:
  ncolors:
    description: "Change your username color in chat!"
    permission: ncolors.use

permissions:
  ncolors.use:
    description: Use Nickname Colors
    default: op
  red.ncolors:
    description: Use Red Nickname Color
    default: op
  blue.ncolors:
    description: Use Blue Nickname Color
    default: op
  yellow.ncolors:
    description: Use Yellow Nickname Color
    default: op
  orange.ncolors:
    description: Use Orange Nickname Color
    default: op
  purple.ncolors:
    description: Use Purple Nickname Color
    default: op

